language: python
python:
 - "2.6"
 - "2.7"
env:
 - DJANGO_VERSION=1.4.8
 - DJANGO_VERSION=1.5.4
 - DJANGO_VERSION=1.6b4
install:
 - pip install -q git+https://github.com/django/django.git@${DJANGO_VERSION}#egg=Django
 - pip install -q -r travis.txt --use-mirrors
script: fab test
